version: "3.8"
services:
  frontend:
    container_name: frontend
    env_file:
      - ./.env
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${FE_PORT}
      - API_HOST=backend
      - API_PORT=${BE_PORT}
    volumes:
      - ./frontend/:/app
      - node-modules-store:/app/node_modules
    ports:
      - ${FE_PORT}:8888
    depends_on:
      - backend

  backend:
    container_name: backend
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/:/app
      - bundle-store:/usr/local/bundle
    ports:
      - ${BE_PORT}:3000
    depends_on:
      - db

  db:
    container_name: db
    env_file:
      - ./.env
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  mysql-db:
  bundle-store:
  node-modules-store:
