FROM ruby:3.3.3-slim-bullseye

WORKDIR /api

RUN apt-get update -qq \
	    && apt-get install -y \
		build-essential \
		default-libmysqlclient-dev \
        && apt-get clean -y \
	    && rm -rf /var/lib/apt/lists/* \
	    && gem install rails -v 7.1.3.2 \
	    && gem install bundler -v 2.5.10

COPY Gemfile /api/Gemfile
COPY Gemfile.lock /api/Gemfile.lock

RUN bundle install

COPY . /api

EXPOSE 3000

ENTRYPOINT ["sh", "entrypoint.sh"]
